[package]
name = "consumable_vec"
version = "0.3.0"
edition = "2018"
authors = ["Dominik Tacke <dominik.tacke@siemens.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
len-trait="0.6.1"

