[package]
name = "at_reply_parser"
version = "0.1.0"
edition = "2018"
authors = ["domtac <tacdom-github@gmail.com"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
len-trait="0.6.1"

